# 各环境下通用配置
spring:
  main:
    # 此应用不以任何容器方式运行
    web-application-type: none
  application:
    name: project-skeleton-server
logging:
  config: file:./config/logback-spring.xml
  file:
    path: logs/
    # 日志文件前缀名
    name: ${spring.application.name}
    # 历史文件存储天数
    max-history: 30
    # 单个文件大小上限,超此限制将滚动保存
    max-size: 10MB
    # 历史日志总大小上限
    total-size-cap: 2GB
  level:
    # RootLogger 日志级别阈值
    root: INFO

custom-config:
  file:
    name: custom-config1.properties
    path: file:./config/custom-config1.properties
---
# 开发环境使用的配置
spring:
  profiles: dev
grpc:
    server:
      port: 10086
logging:
  config: classpath:logback-spring.xml
custom-config:
  file:
    name: custom-config1.properties
    path: classpath:custom-config1.properties
---
# 测试环境使用的配置
spring:
  profiles: test
grpc:
  server:
    port: 10086
---
# 生产环境使用的配置
spring:
  profiles: prod | default
grpc:
  server:
    port: 10086
---
